{% set name = "ctapipe-io-magic" %}
{% set version = "0.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ctapipe_io_magic-{{ version }}.tar.gz
  sha256: 29c6f21a03042c76bc8497beedb385eb5afba91b4a67f06a8c2423619a2991a7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0.3
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >={{ python_min }}
    - astropy-base >=6.1,<8.dev0
    - ctapipe >=0.25.0,<0.27.dev0
    - numpy >=1.22
    - uproot >=5.0,<6.dev0
    - scipy <1.14

test:
  imports:
    - ctapipe_io_magic
  commands:
    - pip check
    - python -c "from ctapipe_io_magic import __version__; print(__version__)"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cta-observatory/ctapipe_io_magic
  summary: ctapipe plugin for reading calibrated MAGIC files
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aleberti
