{% set name = "ctapipe-io-magic" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ctapipe_io_magic-{{ version }}.tar.gz
  sha256: 76d0a4ba788febae32314a178d90cd592a137d1d9edf454b22a5d1541e7c0d73

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64.0.3
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.8
    - astropy >=5.0,<6.dev0
    - ctapipe >=0.19.0,<0.20.dev0
    - numpy >=1.22
    - uproot >=5.0,<6.dev0

test:
  imports:
    - ctapipe_io_magic
  commands:
    - pip check
    - python -c "from ctapipe_io_magic import __version__; print(__version__)"
  requires:
    - pip

about:
  home: https://github.com/cta-observatory/ctapipe_io_magic
  summary: ctapipe plugin for reading calibrated MAGIC files
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aleberti
